fix: limit grip events to 1 hour difference
FORTH-ICS-INSPIRE/artemis-web pull request #133
Opened 2021-11-02 14:00 UTC by CuriouzK0d3r

### Description of PR

Added a condition to limit grip events association to 1 hour time window.

What component(s) does this PR affect?

  - [ ] Back-End (Node.js, Next.js)
  - [x] Front-End (React.js)
  - [ ] Theming (CSS, React theme)
  - [ ] Build System
  - [ ] Docs
  
  
  
  Does the PR require changes on other components? If yes, please mark the components:
  
  - [ ] Back-End (Node.js, Next.js)
  - [ ] Front-End (React.js)
  - [ ] Theming (CSS, React theme)
  - [ ] Build System
  - [ ] Docs
  
  
  
### Related Issue
  
  
  
  
  
  
  Resolves #
  
### Solution
  
  
### Type
  
  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)
  - [ ] Docs update
  - [ ] None of the above
  
  
  
### Checklist:
  
  - [ ] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
  - [ ] This change requires a change in the documentation.
  - [ ] I have updated the documentation accordingly.
  >)`>>>)>

2021-11-11 16:50 UTC, vkotronis approved these changes
LGTM, please remove `console.log` statements if we do not need them

2021-11-12 11:17 UTC, vkotronis commented on apps/artemis-web/components/hijack-info/hijack-info.tsx
> +        console.log(eventData)
TODO: remove

2021-11-12 14:04 UTC, vkotronis requested changes
Please merge the current master branch so that we see only the actual changes in the PR

2021-11-12 16:56 UTC, CuriouzK0d3r commented
> Please merge the current master branch so that we see only the actual changes in the PR

I synced :)

2021-11-22 18:55 UTC, vkotronis approved these changes
LGTM

2021-11-22 18:58 UTC, merged